<?php

namespace HubletoApp\Community\Warehouses\Controllers;

class Locations extends \HubletoMain\Core\Controllers\Controller
{

  /* uncomment this if you want to return JSON string
  public int $returnType = \ADIOS\Core\Controller::RETURN_TYPE_JSON;

  public function renderJson(): array
  {
    return [];
  }
  */

  public function prepareView(): void
  {
    parent::prepareView();

    // these parameters are generated by the `php hubleto` command
    $this->viewParams['now'] = date('Y-m-d H:i:s');
    $this->viewParams['randomNumber'] = rand(1, 1000);

    $this->setView('@HubletoApp:Community:Warehouses/Locations.twig');
  }

}
