<?php

namespace Hubleto\App\Community\Worksheets\Controllers;

class Activities extends \Hubleto\Erp\Controller
{
  // Uncomment this if you want to make your controller public
  // public bool $requiresAuthenticatedUser = false;

  // Uncomment this if you want to have full control over the response content
  // (default Hubleto's desktop will not be rendered)
  // public bool $hideDefaultDesktop = true;

  public function prepareView(): void
  {

    // Uncomment this if you want your controller be hookable
    $this->hookManager()->run('controller:prepare-view-start', [$this]);

    parent::prepareView();

    // these parameters are generated by the `php hubleto` command
    $this->viewParams['now'] = date('Y-m-d H:i:s');
    $this->viewParams['randomNumber'] = rand(1, 1000);

    $this->setView('@Hubleto:App:Community:Worksheets/Activities.twig');

    // Uncomment this if you want your controller be hookable
    $this->hookManager()->run('controller:prepare-view-end', [$this]);
  }

}
