<?php

namespace Hubleto\App\Community\Leads\Controllers;

class Levels extends \Hubleto\Erp\Controller
{
  public function getBreadcrumbs(): array
  {
    return array_merge(parent::getBreadcrumbs(), [
      [ 'url' => 'settings', 'content' => $this->translate('Settings') ],
      [ 'url' => '', 'content' => $this->translate('Lead Levels') ],
    ]);
  }

  public function prepareView(): void
  {
    parent::prepareView();

    // these parameters are generated by the `php hubleto` command
    $this->viewParams['now'] = date('Y-m-d H:i:s');
    $this->viewParams['randomNumber'] = rand(1, 1000);

    $this->setView('@Hubleto:App:Community:Leads/Levels.twig');
  }

}
