<?php

namespace Hubleto\App\Community\Warehouses\Controllers;

class Warehouses extends \Hubleto\Erp\Controller
{
  public function prepareView(): void
  {
    parent::prepareView();

    // these parameters are generated by the `php hubleto` command
    $this->viewParams['now'] = date('Y-m-d H:i:s');
    $this->viewParams['randomNumber'] = rand(1, 1000);

    $this->setView('@Hubleto:App:Community:Warehouses/Warehouses.twig');
  }

}
