rewriteBase: /hubleto/demo
rootUrl: http://localhost/hubleto/demo
srcUrl: http://localhost/hubleto/demo/vendor/hubleto/main
dbHost: localhost
dbUser: root
dbPassword: ''
dbName: hbl_demo
dbCodepage: utf8mb4
accountFullName: Hubleto Demo Ltd.
adminName: Gill
adminFamilyName: Bates
adminNick: gill-b
adminEmail: demo@example.com
adminPassword: demo

# Uncomment following lines if you want to have full control over
# what apps will be installed. Example below installs minimal set
# of apps.
# packagesToInstall: no-package
appsToInstall:
  # \HubletoApp\Community\OAuth\Loader: { sidebarOrder: 99997 }
  \HubletoApp\Community\Settings\Loader: { sidebarOrder: 99997 }
  \HubletoApp\Community\Tools\Loader: { sidebarOrder: 99997 }
  \HubletoApp\Community\Desktop\Loader: { }
  \HubletoApp\Community\Cloud\Loader: { sidebarOrder: 99999 }
  \HubletoApp\Community\Usage\Loader: { }
  \HubletoApp\Community\Documents\Loader: { sidebarOrder: 120 }
  \HubletoApp\Community\Customers\Loader: { sidebarOrder: 101 }
  \HubletoApp\Community\Contacts\Loader: { }
  \HubletoApp\Community\Calendar\Loader: { sidebarOrder: 110 }
  \HubletoApp\Community\Reports\Loader: { sidebarOrder: 99996 }
  \HubletoApp\Community\About\Loader: { sidebarOrder: 99998 }
  \HubletoApp\Community\Help\Loader: { sidebarOrder: 99998 }

  \HubletoApp\Community\Suppliers\Loader: { sidebarOrder: 200 }
  \HubletoApp\Community\Products\Loader: { sidebarOrder: 201 }
  \HubletoApp\Community\Warehouses\Loader: { sidebarOrder: 202 }
  \HubletoApp\Community\Inventory\Loader: { sidebarOrder: 203 }
  \HubletoApp\Community\Campaigns\Loader: { sidebarOrder: 205 }
  \HubletoApp\Community\Leads\Loader: { sidebarOrder: 210 }
  \HubletoApp\Community\Pipeline\Loader: { sidebarOrder: 220 }
  \HubletoApp\Community\Deals\Loader: { sidebarOrder: 230 }
  \HubletoApp\Community\Orders\Loader: { sidebarOrder: 320 }
  \HubletoApp\Community\Dashboards\Loader: { sidebarOrder: 330 }
  \HubletoApp\Community\Notifications\Loader: { sidebarOrder: 125 }
  \HubletoApp\Community\Mail\Loader: { sidebarOrder: 125 }
  \HubletoApp\Community\Discussions\Loader: { sidebarOrder: 126 }
  \HubletoApp\Community\Projects\Loader: { sidebarOrder: 125 }
  \HubletoApp\Community\Tasks\Loader: { sidebarOrder: 125 }
  \HubletoApp\Community\Worksheets\Loader: { sidebarOrder: 125 }
  \HubletoApp\Community\Events\Loader: { sidebarOrder: 125 }
  \HubletoApp\Community\Developer\Loader: { sidebarOrder: 521 }
  # \HubletoApp\Premium\Bids\Loader: { sidebarOrder: 520 }


# Uncomment following lines if you want to customize look & feel
# of your Hubleto
# extraConfigEnv:
#   uiTheme: green-orange
#   logoUrl: assets/custom/images/my-hubleto.png
#   welcomeSplashImageUrl: assets/custom/images/my-hubleto.png
#   availableLanguages: []
#   appTitle: My Hubleto - Fully customized Hubleto
#   sidebarGroups:
#     crm:
#       title: CRM
#       icon: fas fa-id-card-clip
#     maintenance:
#       title: Maintenance
#       icon: fas fa-cog
